### ISSUE TITLE
intermittent error: deque mutated during iteration

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#627]
```
neurostore     | RuntimeError('deque mutated during iteration')
neurostore     | Traceback (most recent call last):
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
neurostore     |     await app(scope, receive, sender)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/swagger_ui.py", line 220, in __call__
neurostore     |     await self.router(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
neurostore     |     await route.handle(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 459, in handle
neurostore     |     await self.app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 775, in __call__
neurostore     |     await self.default(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/swagger_ui.py", line 233, in default_fn
neurostore     |     await self.app(original_scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
neurostore     |     await self.simple_response(scope, receive, send, request_headers=headers)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
neurostore     |     await self.app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/routing.py", line 153, in __call__
neurostore     |     await self.router(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
neurostore     |     await route.handle(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 459, in handle
neurostore     |     await self.app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
neurostore     |     await route.handle(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
neurostore     |     await self.app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/routing.py", line 47, in __call__
neurostore     |     await self.next_app(original_scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 268, in __call__
neurostore     |     return await operation(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/security.py", line 95, in __call__
neurostore     |     await self.next_app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 268, in __call__
neurostore     |     return await operation(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/request_validation.py", line 142, in __call__
neurostore     |     await self.next_app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 268, in __call__
neurostore     |     return await operation(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/response_validation.py", line 127, in __call__
neurostore     |     await self.next_app(scope, receive, wrapped_send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/lifespan.py", line 26, in __call__
neurostore     |     await self.next_app(scope, receive, send)
neurostore     |   File "/neurostore/neurostore/core.py", line 26, in __call__
neurostore     |     await self.app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 268, in __call__
neurostore     |     return await operation(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/middleware/context.py", line 25, in __call__
neurostore     |     await self.next_app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/apps/flask.py", line 149, in __call__
neurostore     |     return await self.asgi_app(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 157, in __call__
neurostore     |     return await responder(scope, receive, send)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 191, in __call__
neurostore     |     await self.loop.run_in_executor(
neurostore     |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
neurostore     |     result = self.fn(*self.args, **self.kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 244, in wsgi
neurostore     |     for chunk in self.app(environ, start_response):
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
neurostore     |     response = self.handle_exception(e)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
neurostore     |     response = self.full_dispatch_request()
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
neurostore     |     rv = self.handle_user_exception(e)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
neurostore     |     rv = self.dispatch_request()
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
neurostore     |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/apps/flask.py", line 66, in __call__
neurostore     |     return self.fn(*args, **kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/decorators/main.py", line 134, in wrapper
neurostore     |     return decorated_function(request)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/decorators/response.py", line 171, in wrapper
neurostore     |     handler_response = function(*args, **kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/decorators/parameter.py", line 87, in wrapper
neurostore     |     return function(**kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/connexion/decorators/main.py", line 123, in wrapper
neurostore     |     return function(*args, **kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask_caching/__init__.py", line 399, in decorated_function
neurostore     |     rv = self._call_fn(f, *args, **kwargs)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask_caching/__init__.py", line 175, in _call_fn
neurostore     |     return ensure_sync(fn)(*args, **kwargs)
neurostore     |   File "/neurostore/neurostore/resources/base.py", line 355, in get
neurostore     |     record = q.filter_by(id=id).first_or_404()
neurostore     |   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/query.py", line 44, in first_or_404
neurostore     |     rv = self.first()
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2824, in first
neurostore     |     return self.limit(1)._iter().first()
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
neurostore     |     result = self.session.execute(
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
neurostore     |     result = conn._execute_20(statement, params or {}, execution_options)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
neurostore     |     return meth(self, args_10style, kwargs_10style, execution_options)
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
neurostore     |     return connection._execute_clauseelement(
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1590, in _execute_clauseelement
neurostore     |     self.dispatch.after_execute(
neurostore     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 333, in __call__
neurostore     |     for fn in self.listeners:
neurostore     | RuntimeError: deque mutated during iteration
```

**Comment by adelavega** [comment]
@jdkent still an issue?
